Microapp BLE - Scanning and filtering advertisements
crownstone/crownstone-microapp pull request #7
Opened 2021-11-26 10:28 UTC by martijnvandermarel

Please review carefully!

Features:
- Registering scanned device event handlers through bluenet.
- Filtering scanned advertisements on MAC address, device name and service data UUID.
- An example which filters advertisements from a BLE temperature sensor and prints temperature data over Serial.

Keep in mind that bluenet firmware needs to be the accompanying bluenet branch: https://github.com/martijnvandermarel/bluenet/tree/microapp-ble. In addition, for testing with ble_example.ino you will need a Xiaomi Thermometer LYWSD03MMC, reprogrammed with custom firmware as described here: https://github.com/atc1441/ATC_MiThermometer (such that service data is not encrypted).

That said, the added changes should of course work for any BLE device sending out advertisements, so feel free to test with your own BLE device.

2021-11-26 11:21 UTC, mrquincle commented
It will be officially reviewed by @vliedel (but I'll take a short look later today).

2021-11-27 14:21 UTC, mrquincle requested changes
Great work. Needs a bit of fine tuning. Can be merged after that (and when https://github.com/crownstone/bluenet/pull/143 is accepted).

2021-11-27 14:21 UTC, mrquincle commented on ble_example.ino
> +#include <ArduinoBLE.h>
Place in examples/ folder.

2021-11-27 14:21 UTC, mrquincle commented on ble_example.ino
> +    Serial.println("my_callback_func: ");
Use same indentation as the other files in this project. Which is tabs.

2021-11-27 14:21 UTC, mrquincle commented on include/ArduinoBLE.h
> +    bool isScanning();
This function has not been implemented. Make sure to the user if this takes a roundtrip to the firmware or if it just accesses local state.

2021-11-27 14:21 UTC, mrquincle commented on src/ArduinoBLE.cpp
> +void Ble::addFilter(BleFilter filter)
Pass by reference instead.

2021-11-27 14:21 UTC, mrquincle commented on src/ArduinoBLE.cpp
> +void Ble::removeFilter()
Too much copying around.

2021-11-27 14:21 UTC, mrquincle commented on src/ArduinoBLE.cpp
> +BleFilter Ble::getFilter()
Returns copy of object, should return a reference.

2021-11-29 08:53 UTC, vliedel commented
So, after all the detailed comments, I think the bigger questions are:
-  Do we want to mimic the [ArduinoBLE](https://www.arduino.cc/en/Reference/ArduinoBLE) library, or make our own API?
  - ArduinoBLE makes use of strings a lot, that will increase the binary size.
  - ArduinoBLE only allows you to filter by 1 type at a time. This reduces flexibility for the user, but probably decreases the binary size.
- Do we want a callback for scanned devices, or buffer them (like in ArduinoBLE)?
- What code style do we use for this repository? Right now it's not coherent. We might also consider a different style for the .ino examples.

2021-11-29 08:55 UTC, vliedel requested changes
Let's first discuss the bigger questions and then adjust based on the outcome :)

2021-11-29 08:55 UTC, vliedel commented on ble_example.ino
> +    uint8_t adType = dev.data[1];
There are multiple ad types in the advertisement payload.

2021-11-29 08:55 UTC, vliedel commented on ble_example.ino
> +            Serial.println(localName,dev.dlen-2);
The data length of this ad type is `dev.data[0] - 1` See for example here: https://github.com/crownstone/bluenet/blob/master/docs/ASSET_FILTERING.md#ble-advertisement

2021-11-29 08:55 UTC, vliedel commented on ble_example.ino
> +            uint8_t UUID[2] = {dev.data[3], dev.data[2]};
You probably want to check the data size and service data UUID before assuming how to interpret the data.

2021-11-29 08:55 UTC, vliedel commented on src/ArduinoBLE.cpp
> +            uint8_t type = dev.data[1];
Same as in the example: there can be multiple AD fields in an advertisement.

2021-11-29 08:55 UTC, vliedel commented on src/ArduinoBLE.cpp
> +            if ((dev.dlen - 2) != strlen(filter.completeLocalName)) return; // device name and filter name don't have same length
Same as in the example: the size of this AD field data can be less than `dlen - 2`.

2021-11-29 08:55 UTC, vliedel commented on src/ArduinoBLE.cpp
> +            if ((dev.dlen - 2) != strlen(filter.completeLocalName)) return; // device name and filter name don't have same length
Also: maybe cache strlen() in the filter.

2021-11-29 08:55 UTC, vliedel commented on src/microapp.c
> +bool memcmp(const void *bufA, const void *bufB, uint8_t len)
Check the internet how to implement memcmp :)

2021-11-29 08:55 UTC, vliedel commented on include/ArduinoBLE.h
> +    const char* completeLocalName;
This will fail if the user creates a temp string. Only the pointer is stored in the struct, and the string it points to may already be gone.

2021-11-29 08:55 UTC, vliedel commented on include/ArduinoBLE.h
> +    BleFilterType filterType;
If the filter can only be of 1 type, the data members can be put in a union.

2021-11-29 09:05 UTC, mrquincle commented
> So, after all the detailed comments, I think the bigger questions are:
> 
>     * Do we want to mimic the [ArduinoBLE](https://www.arduino.cc/en/Reference/ArduinoBLE) library, or make our own API?
> 
>     * ArduinoBLE makes use of strings a lot, that will increase the binary size.
> 
>     * ArduinoBLE only allows you to filter by 1 type at a time. This reduces flexibility for the user, but probably decreases the binary size.
> 
>     * Do we want a callback for scanned devices, or buffer them (like in ArduinoBLE)?
> 
>     * What code style do we use for this repository? Right now it's not coherent. We might also consider a different style for the .ino examples.

I have a strong preference with starting what people might already know. We can later on come up with an "advanced" bluenet/crownstone library that does a lot of things that cannot be done with the more simple calls.

2021-12-06 10:06 UTC, martijnvandermarel commented
Should be ready for a second round of review :)

2021-12-07 13:33 UTC, vliedel requested changes
Yes, much better :)

- I'm not sure about the use of `data_ptr_t` yet, nor what else to use.
- The String class looks a bit odd as it is: when copying a string, it doesn't copy the data. That will lead to pointers to invalid data.
- Cache your results, especially when you already use the ram.
- Go over some files to fix the code style.

2021-12-07 13:33 UTC, vliedel commented on src/BleUtils.cpp
> +	char* p = (char*) uuid_str;
This shouldn't be needed: you can change `convertTwoHexCharsToByte` to take a const pointer.

2021-12-07 13:33 UTC, vliedel commented on src/BleUtils.cpp
> +		byte[i] = convertTwoHexCharsToByte(p);
```suggestion
		byte[i] = convertTwoHexCharsToByte(uuid_str + 2 * i);
```

2021-12-07 13:33 UTC, vliedel commented on src/BleDevice.cpp
> +bool BleDevice::hasLocalName() {
Use cached result when possible?

2021-12-07 13:33 UTC, vliedel commented on src/BleDevice.cpp
> +String BleDevice::localName() {
Use cached result?

2021-12-07 13:33 UTC, vliedel commented on src/BleUtils.cpp
> +		p++;
No need for `p`?
```suggestion
	for (uint8_t i = 0; i < 2; i++) {
		if (c[i] >= 0 && c[i] <= 9) {
			*res = c[i] + '0';
		}
		else if (c[i] >= 0xA && c[i] <= 0xF) {
			*res = c[i] + 'A' - 10;
		}
```

2021-12-07 13:33 UTC, vliedel commented on examples/ble_peripheral_xiaomi_thermometer.ino
> +		Serial.println("\tService data");
Give a good example, check length =]
```
if (serviceData.len == 12) {

}
```

2021-12-07 16:51 UTC, mrquincle approved these changes
Some minor things.

2021-12-08 08:52 UTC, vliedel commented on include/ArduinoBLE.h
> +	union {
What do you mean with being explicit about it?
This is a struct that's used internally, so it can change freely. I don't really see the harm of changing the position of `len`. When it does turn into protocol, it's better to put `len` at the front indeed.

2021-12-08 08:57 UTC, mrquincle commented on include/ArduinoBLE.h
> +	union {
Sure, now it's internal. Until it isn't. :-)

2021-12-08 10:28 UTC, martijnvandermarel commented on include/microapp.h
> +char* strcpy (char* dest, const char* src);
`strncpy` would basically be the same as `memcpy` then. Why not use that under the hood?

2021-12-08 12:29 UTC, mrquincle commented on include/microapp.h
> +char* strcpy (char* dest, const char* src);
Of course, like I already described, my preference is not to rely on null-bytes, so `memcpy` which by design includes a size parameter is perfect in my opinion. 

A `strncpy` would copy up to `n` or up to the null-byte whatever comes first. So, it's slightly different from `memcpy`.

2021-12-08 15:07 UTC, martijnvandermarel commented on include/ArduinoBLE.h
> +struct BleFilter {
Why? The BleFilter is used only within the microapp.

2021-12-08 15:15 UTC, mrquincle commented on include/ArduinoBLE.h
> +struct BleFilter {
Ah, okay. Check. That wasn't clear to me. 

- Comments preceding structs (just handle them as classes) would be nice. 
- I would then say that it's doing premature size optimization. I'd remove the union.

2021-12-09 12:42 UTC, merged

2021-12-09 12:42 UTC, vliedel commented
I'm assuming you tested it :D