Updated API wish Mesh Presence awareness and Power usage
crownstone/crownstone-microapp pull request #8
Opened 2021-12-15 15:28 UTC by mPlagge

Added PowerUsage Presence and Mesh classes for API functionality. Also added example code for them.

2021-12-16 09:41 UTC, vliedel requested changes
In general:
- Please change your code so it adheres to the [code style](https://github.com/crownstone/bluenet/blob/master/docs/CODE_STYLE.md)
- Rename, or split up api_examples.ino, so the name(s) tells what example it is. Or merge into the existing example.
- In retrospect, the mesh structs are not very handy, but we can refactor them later.

2021-12-16 09:41 UTC, vliedel commented on include/Mesh.h
> +// #include <stdio.h>
Remove commented out includes.

2021-12-16 09:41 UTC, vliedel commented on src/Mesh.cpp
> +uint8_t CMD_SIZE = 1;
Can be a static const.

2021-12-16 09:41 UTC, vliedel commented on src/Presence.cpp
> +#define MAX_ROOMS 64
Can be a static const.

2021-12-20 08:30 UTC, mPlagge commented
Thanks for your points of feedback. They are fixed in the latest commit.

2021-12-20 13:01 UTC, vliedel requested changes
Getting there =]
Needs documentation of the public methods, and style isn't done yet (especially variable names).

2021-12-23 11:14 UTC, mPlagge commented
Changed the wrong info in the docstrings in the lastest commit.

2022-04-25 12:41 UTC, mrquincle commented
@vliedel is this PR outdated? Can It be closed?

2022-05-03 11:51 UTC, vliedel commented
No, this is outdated by now, and I think the API is already included (though differently).

2022-05-03 11:51 UTC, closed without merging